name: wsgup
description: Console programs for testing Wireless@SG credentials decryption and recovery.
version: 1.0.0
repository: https://github.com/gyk4j/wsgup

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  hex: ^0.2.0
  pointycastle: ^3.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
